/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    CartItemList: typeof import('./src/components/CartItemList.vue')['default']
    DrawerHeader: typeof import('./src/components/DrawerHeader.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    InfoBlock: typeof import('./src/components/InfoBlock.vue')['default']
    ItemComparison: typeof import('./src/components/ProductComparison.vue')['default']
    MainCard: typeof import('./src/components/MainCard.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MatchCard: typeof import('./src/components/matches/MatchCard.vue')['default']
    PlayerAvatar: typeof import('./src/components/players/PlayerAvatar.vue')['default']
    ProductComparison: typeof import('./src/components/ProductComparison.vue')['default']
    RankedHub: typeof import('./src/components/RankedHub.vue')['default']
    RankedStreamHub: typeof import('./src/components/RankedStreamHub.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunCard: typeof import('./src/components/runs/RunCard.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
